wandb:
  log: true
  project: 'rrr-clip'
  notes: ''

experiment:
  dataset: 'cub'
  im_size: 224
  ntasks: 11
  total_num_classes: 200
  approach: 'rrr'
  raw_memory_only: false
  xai_memory: true
  use_memory: true
  segmentation: false
  augmentation: true
  memory_budget: 500
  fscil: true
  lr_multiplier: 2
  fs_batch: 10
  fs_batchfs_batch: 10
  seed: 0

device:
  name: 'cuda'
  multi: false
  workers: 0

architecture:
  backbone: 'resnet18'
  pretrained: true
  multi_head: false

saliency:
  method: 'clip'
  upsample: false
  loss: 'l1'
  regularizer: 100
  lr: 0.0005
  MODEL_TYPE: 'RN50'
  TARGET_LAYER: "layer4.2.relu"
  PROMPTS: ["an image of a bird"]

train:
  nepochs: 70
  lr: 0.001
  lr_factor: 3
  lr_patience: 5
  batch_size: 64
  memory_batch_size: 5
  pc_valid: 0
  wd: 0.1
  optimizer: 'radam'
  shuffle_tasks: false
  gamma: 0.2
  task_loss_reg: 1
  l1_reg: false
  l1_reg_factor: 1e-5
  num_runs: 1

path:
  data: '../data'
  checkpoint: './checkpoints/'
  output: ''
